spring.application.name=travel-app
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
weather.api.key=06fa5a90da6801b7e7d922e18c5156c9 
currency.api.key=2f02c8d3bb3dfff37635b59e
flight.api.key=28bd132e47f65ddda11941999fbbe871
jwt.secret=voyit-secret-key-that-is-long-enough-for-hs256-algorithm-minimum-256-bits
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
