POST http://localhost:8080/trips
Content-Type: application/json

{
  "cityName": "Bangkok",
  "countryName": "Thailand",
  "startDate": "2026-10-08",
  "returnDate": "2026-11-09"

}

###
GET http://localhost:8080/trips/1


###
POST http://localhost:8080/trips/1/packingitems
Content-Type: application/json

{
  "name": "Passport"
}

###
GET http://localhost:8080/trips/1/packingitems

###

PUT http://localhost:8080/packingitems/2
Content-Type: application/json

{
  "name": "charger"
}

###
DELETE http://localhost:8080/packingitems/2




