POST http://localhost:8080/trips
Content-Type: application/json

{
  "cityName": "Bangkok",
  "countryName": "Thailand",
  "startDate": "2026-10-08",
  "returnDate": "2026-11-09"

}

###
GET http://localhost:8080/trips/1

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Katharina",
  "email": "kath4393@gmail.com",
  "password": "Duddi2402",
  "profilePhoto": "N/A"
}


###

GET http://localhost:8080/users/1

###

PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Katha",
  "email": "kath4393@gmail.com",
  "password": "Duddi240285",
  "profilePhoto": "N/A"
}

###



